www/dsearch/search/urls.py
from django.conf.urls import patterns, url

from search import views

urlpatterns = patterns('',
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^browse/', views.browse, name='browse'),
    url(r'^search/', views.whoosh_search, name='search'),
)

www/dsearch/search/models.py
from django.db import models


class Image(models.Model):
    ''' the original test images
    '''
    imageid = models.IntegerField(unique=True)
    filename = models.ImageField()
    def __unicode__(self):
        return self.filename.name

class ImageHist(models.Model):
    ''' the graphical representations of the test images
    '''
    histid = models.IntegerField(unique=False)
    filename = models.ImageField()
    bins = models.IntegerField(unique=False)
    def __unicode__(self):
        return self.filename.name

class Result(models.Model):
    ''' result of a browse or search action
    '''
    image = models.ForeignKey(Image)
    score = models.FloatField()
    def __unicode__(self):
        return self.result.filename.name + u'[%.3f]'%self.score

www/dsearch/search/forms.py
from django import forms

class GetImageRangesForm(forms.Form):
    imageids = forms.CharField(required=False, label='imageids',\
            widget=forms.Textarea(attrs={'class' : 'form-control', 'rows' : 3,\
                                         'placeholder' : 'image ranges e.g. 1-3,4,5,9-12'}))

BIN_CHOICES = (('32', '32',),('64','64',),('128','128',))

TRANSFORMER_CHOICES = (('gaussian', 'gaussian',),('fourier','fourier',))

class GetImageForm(forms.Form):
    imageids= forms.IntegerField(required=False, label='imageids',
            widget=forms.TextInput(attrs={'class' : 'form-control',
            'placeholder' : 'Sorry, the search feature doesn\'t work well yet, but we\'re hard at work :)'}))
    
    bins= forms.ChoiceField(choices=BIN_CHOICES)

    transformer= forms.ChoiceField(choices=TRANSFORMER_CHOICES)

www/dsearch/search/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist

from django.views.generic import TemplateView

from search.forms import GetImageForm, GetImageRangesForm
from search.models import Image, ImageHist, Result

from imageclef.simplesearch import similarto

#whoosh stuff
from whoosh.index import create_in, open_dir
from whoosh.fields import ID, KEYWORD, Schema
from whoosh.qparser import QueryParser, OrGroup
import indexer.histograms as ih
import os
import numpy as np
import time
from scipy.fftpack import dct

class HomeView(TemplateView):
    template_name = "search/home.html"


def browse(request):

    def _process(imageidranges):
        _images = None
        if not imageidranges:
            return images

        ranges = (x.split("-") for x in imageidranges.split(","))
        imageids = [i for r in ranges for i in range(int(r[0]), int(r[-1]) + 1)]

        _images = []
        for imageid in imageids:
            try:
                nextimage = Image.objects.get(imageid=imageid)
            except ObjectDoesNotExist:
                default_image = Image.objects.get(imageid=0)
                nextimage = Image(imageid=imageid, filename=default_image.filename)
            _images.append(nextimage)
        return _images                                                               

    images = None
    if request.method == 'GET':
        form = GetImageRangesForm(request.GET)
        if form.is_valid():
            imageidranges = form.cleaned_data['imageids']
            images = _process(imageidranges)
    else:
        form = GetImageRangesForm() # An unbound form
    return render(request, 'search/browse.html', {'form': form, 'images' : images })


def whoosh_search(request):
    
    def whoosh(imageid__):

        def indices_as_keywords(n):
            return u' '.join(map(unicode, list(n)))

        class GaussianTransformer(object):
            def __init__(self, d, m, h, random_seed):
                np.random.seed(random_seed)
                self.A = np.random.randn(m, d)
                self.h = h
        
            def transform(self, x):
                return indices_as_keywords(np.nonzero(np.dot(self.A, x)>self.h)[0])
        
        class SparseFFTTransformer(object):
            def __init__(self, d, m, h, random_seed):
                np.random.seed(random_seed)
                self.choices = np.random.choice(m, size=d, replace=False)
                self.signs = 1.0-2.0*np.random.randint(2, size=d)
                self.h = h*np.sqrt(2.)  # equivalent to scaling dct by 1/sqrt(2)
                self.y = np.zeros(m)
        
            def transform(self, x):
                self.y[self.choices] = self.signs*x
                return indices_as_keywords(np.nonzero(dct(self.y)>self.h)[0])
        
        histogram_file = '/var/data/imageclef/histograms/hsv{:d}/1/histo_numbers.json'.format(int(bin_toggle))
        from ujson import load
        with open(histogram_file, 'r') as histogram_json:
            histograms = load(histogram_json)
    
        def normalize_list(l):
            x = np.array(l, dtype=float)
            return x/np.linalg.norm(x)

        normalized_histograms = {k:normalize_list(h) for k, h in histograms.iteritems()}

        params = {
            'd': 128,
            'm': 50000,
            'h': 2.0
        }
        base_data_dir = '/home/treimer/var/data/whoosh_index'

        gaussian_transformer = GaussianTransformer(int(bin_toggle), params['m'], 2.8, random_seed=0)
        sparsefft_transformer = SparseFFTTransformer(int(bin_toggle), params['m'], 2.5, random_seed=0)
        transformer = gaussian_transformer
        #transformer = sparsefft_transformer

        if transformer == gaussian_transformer:
               
            gaussian_index_dir = os.path.join(base_data_dir, 'gaussian/{:d}'.format(int(bin_toggle)))
            gaussian_ix = open_dir(gaussian_index_dir)
            ix = gaussian_ix

        if transformer == sparsefft_transformer:
    
            sparsefft_index_dir = os.path.join(base_data_dir, 'sparsefft/{:d}'.format(int(bin_toggle)))
            sparsefft_ix = open_dir(sparsefft_index_dir)
            ix = sparsefft_ix

        schema = Schema(path=ID(stored=True), content=KEYWORD)

        seed_hist = normalized_histograms[''+`imageid__`+'']

        transform_time = 0
        search_time = 0

        with ix.searcher() as searcher:
            _t = time.time()
            seed = transformer.transform(seed_hist)
            transform_time += (time.time() - _t)
            query = QueryParser("content", ix.schema, group=OrGroup).parse(seed)
            _t = time.time()
            results = searcher.search(query, limit=20)
            search_time += (time.time() - _t)
            results_ = []
            for k, r in enumerate(results):
                result_id = results[k]['path']
                results_.append(int(result_id))

        search_time = ("%.2f" % search_time) 
        return results_, search_time, transform_time

                                                                          
    def _process(results_):

        _images = []
        for imageid in results_:
            try:
                nextimage = Image.objects.get(imageid=imageid)
                nexthist = ImageHist.objects.get(histid = imageid, bins = bin_toggle)
            except ObjectDoesNotExist:
                default_image = Image.objects.get(imageid=0)
                nextimage = Image(imageid=imageid, filename=default_image.filename)
            _images.append(nextimage)
            _images.append(nexthist)
        return _images                                                               
    

    def _process_hists (results_):
                                                                                      
        _hists = []
        for histid in results_:
            try:
                nextimage = ImageHist.objects.get(histid = histid, bins = bin_toggle)
            except ObjectDoesNotExist:
                default_hist = ImageHist.objects.get(histid=0)
                nextimage = ImageHist(histid=histid, filename=default_hist.filename)
            _hists.append(nextimage)
        return _hists                                                               

    images = None
    results_ = None
    hists = None
    search_time = 0
    transform_time = 0
    bin_toggle = None
    transformer_toggle = None

    if request.method == 'POST':
        form = GetImageForm(request.POST)
        if form.is_valid():
            imageid__ = form.cleaned_data['imageids']
            bin_toggle = form.cleaned_data['bins']
            transformer_toggle = form.cleaned_data['transformer']
            
            #bin_toggle = 128
            #transformer_toggle='gaussian'

            results_, search_time, transform_time  = whoosh(int(imageid__))
            images = _process(results_)
            hists = _process_hists(results_)
    else:
        form = GetImageForm() # An unbound form
    return render(request, 'search/whoosh_search.html', {'form': form, 'images' : images, 'hists' : hists, 'search_time' : search_time, 'tranform_time' : transform_time})










            #print result_id, results.score(k), np.dot(seed_hist, normalized_histograms[result_id])
        
        #x = np.array([results.score(k) for k, _ in enumerate(results)])
        #y = np.array([np.dot(seed_hist, normalized_histograms[results[k]['path']]) for k, _ in enumerate(results)])
    
        # print ','.join([results[k]['path'] for k, _ in enumerate(results)])
        #print("search_time: {:.1f} ms\ntransform_time: {:.1f} ms".format(1000.*search_time, 1000.*transform_time))

www/dsearch/templates/search/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>DSearch</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap-3.2.0/dist/css/bootstrap.min.css" rel="stylesheet">

    {% block head_css %}{% endblock %}
    {% block head_js %}{% endblock %}
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Home</a>
          <a class="navbar-brand" href="/browse/">Browse</a>
          <a class="navbar-brand" href="/search/">Search</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
      <div class="jumbotron">
        <h2>Search project</h2>
        <p class="lead">{% block title %}{% endblock %}</p>
      </div>
    </div><!-- /.container -->

    <div class="container">
        {% block content %}{% endblock %}
        <hr>
        <footer>
            <p>&copy; Roger Donaldson &amp Thomas Reimer 2015</p>
        </footer>
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="/static/bootstrap-3.2.0/dist/js/bootstrap.min.js"></script>
    {% block body_js %}{% endblock %}
  </body>
</html>

www/dsearch/templates/search/browse.html
{% extends 'search/base.html' %}

{% block title %}
Image browser
{% endblock %}

{% block content %}
<form role="form" method="get" action=".">
    <div class="form-group">
        <label for="id_imageid">Image Range</label>
        {{ form.imageids }}
    </div>
    <button type="submit" class="btn btn-default">Fetch</button>
</form>
{% if images %}
<h2>Results</h2>
<div class="container" id="results">                                
    <div class="row">
        {% for image in images %}
        <div class="col-md-2">
            <div class="thumbail">
                <img src="{{ MEDIA_URL }}{{ image.filename }}" class="img-responsive"
                    id="{{ image.imageid }}">
            </div>
            <div class="caption">
                [{{ image.imageid }}] {{ image.filename }}
            </div>
        </div>
        {% if forloop.counter|divisibleby:6 %}
    </div>
    <div class="row">
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endif %}
{% endblock %}

{% block js %}
<script>
$(document).ready(function(){
    $('#results').on('click', function(event) {
        window.location.href = '/search/?imageid='+event.target.id
    });
});
</script>
{% endblock %}

www/dsearch/templates/search/home.html
{% extends 'search/base.html' %}

{% block title %}
Welcome
{% endblock %}

{% block content %}
Here's the homepage for running the search project widgets.  Use the navbar above to try out different utilities.
{% endblock %}

www/dsearch/templates/search/search.html
{% extends 'search/base.html' %}

{% block title %}
Image search
{% endblock %}

{% block content %}
<form role="form" method="get" action=".">
    <div class="form-group">
        <label for="id_imageid">SeedId</label>
        {{ form.imageid }}
    </div>
    <button type="submit" class="btn btn-default">Search</button>
</form>
{% if seed %}
<h2>Seed</h2>
<div class="row">
   <div class="col-sm-2 col-md-2">
      <div class="thumbnail">
         <img src='{{MEDIA_URL}}{{ seed.filename }}'>
      </div>
      <div class="caption">
         [{{ seed.imageid }}] {{ seed.filename }}
      </div>
   </div>
</div>

{% if results %}
<h2>Results</h2>
<div class="container" id="results">
    <div class="row">
        {% for result in results %}
        <div class="col-md-2">
            <div class="thumbnail">
                <img src='{{MEDIA_URL}}{{ result.image.filename }}' id="{{ result.image.imageid }}">
            </div>
            <div class="caption">
                [{{ result.image.imageid }}:{{ result.score|floatformat:"2" }}]
                {{ result.image.filename }}
            </div>
        </div>
        {% if forloop.counter|divisibleby:6 %}
    </div>
    <div class="row">
        {% endif %}
        {% endfor %}
    </div>
</div>
{% else %}
<h2>No results</h2>
{% endif %}
{% endif %}
{% endblock %}

{% block js %}
<script>
$(document).ready(function(){
    $('#results').on('click', function(event) {
        window.location.href = '/search/?imageid='+event.target.id
    });
});
</script>
{% endblock %}

def search(request):                                                 
    seed = None
    results = None

    def _process(seedid):
        if not seedid:
            return None, None
        
        try:
            seed = Image.objects.get(imageid=seedid)
        except ObjectDoesNotExist:
            seed = Image(imageid=seedid)
            return seed, None

        results = []
        for resultid,score in similarto(seedid,100,'l2',2000,4000):
            try:
                result = Image.objects.get(imageid=resultid)
            except ObjectDoesNotExist:
                result = Image(imageid=resultid,filename='/')
            results.append(Result(image=result,score=score))

        return seed,results                                             

    if request.method == 'GET':
        form = GetImageForm(request.GET)
        if form.is_valid():
            seedid = form.cleaned_data['imageid']
            seed,results = _process(seedid)
    else:
        form = GetImageForm()
    return render(request, 'search/search.html', { 'form' : form, \
            'seed' : seed, 'results' : results })

www/dsearch/templates/search/whoosh_search.html
{% extends 'search/base.html' %}

{% block title %}
Image Search
{% endblock %}

{% block content %}
<form role="form" method="post" action="."> {% csrf_token %}



<ul class="list-inline">
 <li>
  <h5>Bin Size</h5>
    <label class="radio-inline">
         <input type="radio" name="bins" value="32"> 32
    </label>
    <label class="radio-inline">
         <input type="radio" name="bins" value="64"> 64
    </label>
    <label class="radio-inline">
         <input type="radio" name="bins" value="128"> 128
    </label>                                                      
 </li>
 <li>
  <h5>Transformer</h5>
    <label class ="radio-inline">
      <input type ="radio" name = "transformer" value="gaussian"> Gaussian
    </label>
    <label class ="radio-inline">
      <input type="radio" name="transformer" value="fourier"> Fourier
    </label>                                                                     
 </li>
</ul>                                                                            


    <div class="form-group">
         <label for="id_imageid">Image Range</label>
         {{ form.imageids }}
    </div>
     <button type="submit" class="btn btn-default">Fetch</button>
 </form>
 {% if images %}
 <h2>Results</h2>
 <div class="container" id="results">                                
       <div class="caption">
         Search Time: {{ search_time }} seconds
       </div>
     </li>
   </ul>
     <div class="row">
        {% for image in images %}
        <div class="col-md-2">
            <div class="thumbnail">
                <img src="{{ MEDIA_URL }}{{ image.filename }}" class="img-responsive"
                    id="{{ image.imageid }}">
            </div>
        </div>
        {% if forloop.counter|divisibleby:6 %}
    </div>
    <div class="row">
        {% endif %}
        {% endfor %}
    </div>


</div>
{% endif %}
{% endblock %}

{% block js %}
<script>
$(document).ready(function(){
    $('#results').on('click', function(event) {
        window.location.href = '/search/?imageid='+event.target.id
    });
});
</script>
{% endblock %}                                                                                          